spring.application.name=Kaiwa
server.port=8083

spring.data.mongodb.uri=${MONGO_URI}

logging.level.org.springframework.web=INFO
logging.level.org.springframework.messaging=INFO
logging.level.org.springframework.security=INFO